[[language]]
name = "bibtex"
auto-format = false

[language-server.typst-lsp.config]
exportPdf = "never"

[[language]]
name = "c"
indent = { tab-width = 8, unit = "    " }

[[language]]
name = "cpp"
indent = { tab-width = 8, unit = "    " }
